# Generated by Django 3.1.5 on 2021-01-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='MyFilmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название фильма')),
                ('img', models.ImageField(blank=True, upload_to='static/img', verbose_name='Постер')),
                ('year', models.DateField(verbose_name='Дата выхода')),
                ('rating', models.FloatField(default=0, verbose_name='Оценка')),
                ('comment', models.TextField(max_length=200, verbose_name='Отзыв')),
                ('date_viewed', models.DateField(verbose_name='Дата просмотра')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_films.genresmodel')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['rating'],
            },
        ),
    ]
