# Generated by Django 3.1.5 on 2021-01-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genresmodel',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='myfilmsmodel',
            name='views',
            field=models.FloatField(default=1, verbose_name='Количество просмотров'),
        ),
    ]
