# Generated by Django 3.1.5 on 2021-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_films', '0002_auto_20210111_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfilmsmodel',
            name='views',
            field=models.IntegerField(default=1, verbose_name='Количество просмотров'),
        ),
    ]
